version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "agnara"
      - dependency-name: "agnara-http"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
